name: Build RetroED
on:
  push:
    branches:
      - master

jobs:
  windows-x64:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1
      - name: Download RSDK Reverse
        run : |
          Invoke-WebRequest -Uri "https://github.com/Rubberduckycooly/RSDK-Reverse/archive/9b7daedeba9a481b0b674cf1cb88077401685a1b.zip" -OutFile "rsdkreverse.zip"
          Expand-Archive -Path rsdkreverse.zip -DestinationPath ./
          rm -f ./RSDK-Reverse
          Rename-Item ./RSDK-Reverse-9b7daedeba9a481b0b674cf1cb88077401685a1b RSDK-Reverse
      - name: Build RetroED
        run: |
          msbuild RetroED.sln /p:Configuration=Release /p:Platform=x64 /p:ForceImportBeforeCppTargets="$env:GITHUB_WORKSPACE/props/winactions_x64.props"
      - name: Move artifacts
        run: |
          mkdir artifacts
          move ./build/x64/Release/*.dll ./artifacts 
          move ./build/x64/Release/*.exe ./artifacts
      - name: Upload artifacts
        uses: actions/upload-artifact@v1.0.0  
        with:
          name: v4-windows-x64 
          path: artifacts  
          
